name: glados checkin

on:
  push:
    branches: [main,master]
  schedule:
    - cron: '5 1 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repo'
        uses: actions/checkout@v3.3.0
      - name: 'run script'
        run: echo "RESULT=$(python3 ./glados_check.py)" >> $GITHUB_ENV
      
